# This is a config for E2B sandbox template.
# You can use template ID (wa5s95jdr8b5azvzlcrz) or template name (mark1main) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("mark1main") # Sync sandbox
# sandbox = await AsyncSandbox.create("mark1main") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('mark1main')

team_id = "3bb6e951-6f42-4c8f-83a3-02821c9e4c47"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "mark1main"
template_id = "wa5s95jdr8b5azvzlcrz"
